# Ignore maximize requests from apps
# windowrule = suppress_event fullscreen maximize, match:class .*

# Audacious music player on special workspace
windowrule = workspace special:audacious, match:class audacious

# Satty — floating overlay on top of other windows
windowrule {
    name = float-satty
    match:class = ^(com\.gabm\.satty)$
    float = on
    center = on
}

