[ids]
# REPLACE this line with your actual laptop keyboard ID found via 'sudo keyd monitor'
0001:0001

[main]
# Caps Lock: Tapped = Escape | Held = Control
capslock = overload(control, esc)

# Left-Hand Home Row Mods (S D F)
s = lettermod(alt, s, 150, 200)
d = lettermod(shift, d, 150, 200)
f = lettermod(control, f, 150, 200)

# Right-Hand Home Row Mods (J K L )
j = lettermod(control, j, 150, 200)
k = lettermod(shift, k, 150, 200)
l = lettermod(alt, l, 150, 200)

