include kitty-noctis/noctis-obscuro.conf

font_size 18
font_family JetBrains Mono
enable_ligatures yes

background_opacity 0.7

cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
cursor_trail_color orange

copy_on_select yes

allow_remote_control yes

# first split will be side by side, then
# rest splits will be stacked
enabled_layouts tall, splits, stack

# on launching split, preserve the cwd in new split
# by default, it opens from root directory
map ctrl+shift+enter launch --cwd=current

# pravah dev setup
map ctrl+shift+p>d launch --cwd=current bash -c "~/.config/kitty/scripts/pravah-dev.sh"

